### ISSUE TITLE
(Hide Your Mess Behind ) .deb executable fails to run due to missing libvips libraries

### ISSUE THREAD

**Issue by antoniomtz** [openvinotoolkit/openvino_build_deploy#108]
On  Ubuntu 22.04, when running the .deb executable, it throws the following error:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Could not load the "sharp" module using the linux-x64 runtime
ERR_DLOPEN_FAILED: libvips-cpp.so.42: cannot open shared object file: No such file or directory
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/opt/hide-your-mess-behind/resources/app.asar/node_modules/sharp/lib/sharp.js:113:9)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/opt/hide-your-mess-behind/resources/app.asar/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
```

It appears that the **libvips** libraries required by the sharp module are not included in the .deb package, causing the executable to fail on systems where libvips is not preinstalled.

Steps to Reproduce:
- Download .deb file
- Install the .deb package on a Linux system without libvips preinstalled.
- Attempt to run the application.

Potential solution:
- Install libvips:
`sudo apt install -y libvips-dev`
- Include libvips as dependency for the executable.

**Comment by adrianboguszewski** [comment]
+ problem with chrome-sandbox

**Comment by adrianboguszewski** [comment]
Steps:
1. `npm run dist`
2. `cd dist/linux-unpacked`
3. `./hide-your-mess-behind`

Then you will see the error.

**Comment by antoniomtz** [comment]
> Steps:
> 
> 1. `npm run dist`
> 2. `cd dist/linux-unpacked`
> 3. `./hide-your-mess-behind`
> 
> Then you will see the error (chrome-sandbox)

I was not able to replicate the issue on my system.

**Comment by adrianboguszewski** [comment]
What system do you use? In my case, it's Ubuntu 24.04.
The error:
```
[5318:1204/125628.917656:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/abogusze/repos/openvino_build_deploy/demos/hide_your_mess_behind_demo/dist/linux-unpacked/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
 ```

**Comment by antoniomtz** [comment]
I was able to replicate the issue on a fresh Ubuntu 24.04. I will create a PR for it.
