### ISSUE TITLE
Error in Mobaxterm

### ISSUE THREAD

**Issue by wdsdz** [openvinotoolkit/openvino_build_deploy#96]
Here is the Error Log when i run the code in Mobaxterm.
2024-11-05 19:59:58.279712: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1730807998.300203  429218 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1730807998.306628  429218 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-05 19:59:58.328525: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Framework not specified. Using pt to export the model.
Loading TensorFlow model in PyTorch before exporting.
W0000 00:00:1730808000.512014  429218 gpu_device.cc:2344] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Traceback (most recent call last):
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/transformers/modeling_utils.py", line 575, in load_state_dict
    return torch.load(
           ^^^^^^^^^^^
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/torch/serialization.py", line 1039, in load
    raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
_pickle.UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 118

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/optimum/exporters/tasks.py", line 2115, in get_model_from_task
    model = model_class.from_pretrained(model_name_or_path, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3726, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/transformers/modeling_utils.py", line 585, in load_state_dict
    raise OSError(
OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/convert_and_optimize_asr.py", line 57, in <module>
    convert_asr_model(args.asr_model_type, args.precision, Path(args.model_dir))
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/convert_and_optimize_asr.py", line 37, in convert_asr_model
    ov_model = OVModelForSpeechSeq2Seq.from_pretrained("/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/model/Belle-distilwhisper-large-v2-zh/", export=True, compile=False, load_in_8bit=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/optimum/intel/openvino/modeling_base.py", line 373, in from_pretrained
    return super().from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/optimum/modeling_base.py", line 424, in from_pretrained
    return from_pretrained_method(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/optimum/intel/openvino/modeling_base_seq2seq.py", line 297, in _from_transformers
    main_export(
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/optimum/exporters/openvino/__main__.py", line 308, in main_export
    model = TasksManager.get_model_from_task(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/optimum/exporters/tasks.py", line 2124, in get_model_from_task
    model = model_class.from_pretrained(model_name_or_path, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3892, in from_pretrained
    model, loading_info = load_tf2_checkpoint_in_pytorch_model(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/transformers/modeling_tf_pytorch_utils.py", line 532, in load_tf2_checkpoint_in_pytorch_model
    load_tf_weights(tf_model, tf_checkpoint_path)
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/transformers/modeling_tf_utils.py", line 952, in load_tf_weights
    return load_function(
           ^^^^^^^^^^^^^^
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/transformers/modeling_tf_utils.py", line 961, in load_tf_weights_from_h5
    with h5py.File(resolved_archive_file, "r") as sharded_checkpoint_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/h5py/_hl/files.py", line 561, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gymao/openvino_build_deploy/ai_ref_kits/custom_ai_assistant/venv/lib/python3.11/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (file signature not found)

**Comment by raymondlo84** [comment]
Possible to share the pip freeze?

**Comment by raymondlo84** [comment]
Also the environment and so.
